import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
// Header와 Footer 컴포넌트 import
import Header from '../components/layouts/Header';
import Footer from '../components/layouts/Footer';

// NotoSansKR 폰트 설정 - 모든 페이지에 적용
const notoSansKr = Noto_Sans_KR({
  weight: ['400', '500', '600', '700'], // 다양한 굵기 지원
  subsets: ['latin'], // 한글 포함
  display: 'swap',
  preload: true,
  variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${notoSansKr.className} antialiased`}>
        <Header />
        <main className='container mx-auto py-20'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
